<?php
/**
 * Local Spanish Translation Script
 * 
 * Translates empty msgstr entries in es_ES.po using a built-in dictionary.
 * 
 * Usage: php scripts/translate-po-spanish.php
 */

$po_file = __DIR__ . '/../languages/es_ES.po';

if (!file_exists($po_file)) {
    die("❌ PO file not found: $po_file\n");
}

// Spanish translation dictionary
$dictionary = [
    // ===== COMMON UI =====
    'Save' => 'Guardar',
    'Cancel' => 'Cancelar',
    'Delete' => 'Eliminar',
    'Edit' => 'Editar',
    'Add' => 'Añadir',
    'Update' => 'Actualizar',
    'Close' => 'Cerrar',
    'Back' => 'Atrás',
    'Next' => 'Siguiente',
    'Previous' => 'Anterior',
    'Search' => 'Buscar',
    'Filter' => 'Filtrar',
    'Clear' => 'Limpiar',
    'Reset' => 'Restablecer',
    'Submit' => 'Enviar',
    'Confirm' => 'Confirmar',
    'Yes' => 'Sí',
    'No' => 'No',
    'OK' => 'Aceptar',
    'Loading...' => 'Cargando...',
    'Please wait...' => 'Por favor espere...',
    'Error' => 'Error',
    'Success' => 'Éxito',
    'Warning' => 'Advertencia',
    'Info' => 'Información',
    'None' => 'Ninguno',
    'All' => 'Todos',
    'Select' => 'Seleccionar',
    'Select...' => 'Seleccionar...',
    'Choose' => 'Elegir',
    'Options' => 'Opciones',
    'Actions' => 'Acciones',
    'More' => 'Más',
    'Less' => 'Menos',
    'Show' => 'Mostrar',
    'Hide' => 'Ocultar',
    'View' => 'Ver',
    'Details' => 'Detalles',
    'Summary' => 'Resumen',
    'Total' => 'Total',
    'Subtotal' => 'Subtotal',
    'Tax' => 'Impuesto',
    'Discount' => 'Descuento',
    'Price' => 'Precio',
    'Amount' => 'Cantidad',
    'Quantity' => 'Cantidad',
    'Status' => 'Estado',
    'Active' => 'Activo',
    'Inactive' => 'Inactivo',
    'Enabled' => 'Habilitado',
    'Disabled' => 'Deshabilitado',
    'Default' => 'Predeterminado',
    'Custom' => 'Personalizado',
    'Required' => 'Requerido',
    'Optional' => 'Opcional',
    'Available' => 'Disponible',
    'Unavailable' => 'No disponible',
    'Today' => 'Hoy',
    'Tomorrow' => 'Mañana',
    'Yesterday' => 'Ayer',
    'Now' => 'Ahora',
    'Never' => 'Nunca',
    'Always' => 'Siempre',
    'Name' => 'Nombre',
    'Email' => 'Correo electrónico',
    'Phone' => 'Teléfono',
    'Address' => 'Dirección',
    'City' => 'Ciudad',
    'Country' => 'País',
    'Notes' => 'Notas',
    'Description' => 'Descripción',
    'Title' => 'Título',
    'Date' => 'Fecha',
    'Time' => 'Hora',
    'Duration' => 'Duración',
    'Start' => 'Inicio',
    'End' => 'Fin',
    'From' => 'Desde',
    'To' => 'Hasta',
    'Type' => 'Tipo',
    'Category' => 'Categoría',
    'Image' => 'Imagen',
    'File' => 'Archivo',
    'Upload' => 'Subir',
    'Download' => 'Descargar',
    'Export' => 'Exportar',
    'Import' => 'Importar',
    'Print' => 'Imprimir',
    'Copy' => 'Copiar',
    'Paste' => 'Pegar',
    'Help' => 'Ayuda',
    'About' => 'Acerca de',
    'Version' => 'Versión',
    'Settings' => 'Configuración',
    'General' => 'General',
    'Advanced' => 'Avanzado',
    'Basic' => 'Básico',
    'Profile' => 'Perfil',
    'Account' => 'Cuenta',
    'Password' => 'Contraseña',
    'Login' => 'Iniciar sesión',
    'Logout' => 'Cerrar sesión',
    'Register' => 'Registrarse',
    'Welcome' => 'Bienvenido',
    'Hello' => 'Hola',
    'Goodbye' => 'Adiós',
    
    // ===== DAYS & TIME =====
    'Monday' => 'Lunes',
    'Tuesday' => 'Martes',
    'Wednesday' => 'Miércoles',
    'Thursday' => 'Jueves',
    'Friday' => 'Viernes',
    'Saturday' => 'Sábado',
    'Sunday' => 'Domingo',
    'Mon' => 'Lun',
    'Tue' => 'Mar',
    'Wed' => 'Mié',
    'Thu' => 'Jue',
    'Fri' => 'Vie',
    'Sat' => 'Sáb',
    'Sun' => 'Dom',
    'January' => 'Enero',
    'February' => 'Febrero',
    'March' => 'Marzo',
    'April' => 'Abril',
    'May' => 'Mayo',
    'June' => 'Junio',
    'July' => 'Julio',
    'August' => 'Agosto',
    'September' => 'Septiembre',
    'October' => 'Octubre',
    'November' => 'Noviembre',
    'December' => 'Diciembre',
    'Day' => 'Día',
    'Days' => 'Días',
    'Week' => 'Semana',
    'Weeks' => 'Semanas',
    'Month' => 'Mes',
    'Months' => 'Meses',
    'Year' => 'Año',
    'Years' => 'Años',
    'Hour' => 'Hora',
    'Hours' => 'Horas',
    'Minute' => 'Minuto',
    'Minutes' => 'Minutos',
    'Second' => 'Segundo',
    'Seconds' => 'Segundos',
    
    // ===== BOOKING SYSTEM =====
    'Appointment' => 'Cita',
    'Appointments' => 'Citas',
    'Booking' => 'Reserva',
    'Bookings' => 'Reservas',
    'Reservation' => 'Reserva',
    'Reservations' => 'Reservas',
    'Service' => 'Servicio',
    'Services' => 'Servicios',
    'Customer' => 'Cliente',
    'Customers' => 'Clientes',
    'Staff' => 'Personal',
    'Staff Member' => 'Miembro del personal',
    'Resource' => 'Recurso',
    'Resources' => 'Recursos',
    'Room' => 'Habitación',
    'Rooms' => 'Habitaciones',
    'Location' => 'Ubicación',
    'Locations' => 'Ubicaciones',
    'Calendar' => 'Calendario',
    'Schedule' => 'Horario',
    'Availability' => 'Disponibilidad',
    'Slot' => 'Franja horaria',
    'Time Slot' => 'Franja horaria',
    'Check-in' => 'Entrada',
    'Check-out' => 'Salida',
    'Arrival' => 'Llegada',
    'Departure' => 'Salida',
    'Guest' => 'Huésped',
    'Guests' => 'Huéspedes',
    'Adults' => 'Adultos',
    'Children' => 'Niños',
    'Infant' => 'Bebé',
    'Infants' => 'Bebés',
    
    // ===== STATUS =====
    'Pending' => 'Pendiente',
    'Confirmed' => 'Confirmado',
    'Cancelled' => 'Cancelado',
    'Completed' => 'Completado',
    'No-show' => 'No presentado',
    'In Progress' => 'En progreso',
    'Approved' => 'Aprobado',
    'Rejected' => 'Rechazado',
    'Draft' => 'Borrador',
    'Published' => 'Publicado',
    'Archived' => 'Archivado',
    'Deleted' => 'Eliminado',
    'Open' => 'Abierto',
    'Closed' => 'Cerrado',
    'Booked' => 'Reservado',
    'Available' => 'Disponible',
    'Occupied' => 'Ocupado',
    'Vacant' => 'Vacante',
    'Maintenance' => 'Mantenimiento',
    'Out of Order' => 'Fuera de servicio',
    
    // ===== PAYMENT =====
    'Payment' => 'Pago',
    'Payments' => 'Pagos',
    'Pay' => 'Pagar',
    'Paid' => 'Pagado',
    'Unpaid' => 'No pagado',
    'Partial' => 'Parcial',
    'Refund' => 'Reembolso',
    'Refunded' => 'Reembolsado',
    'Invoice' => 'Factura',
    'Receipt' => 'Recibo',
    'Credit Card' => 'Tarjeta de crédito',
    'Debit Card' => 'Tarjeta de débito',
    'Bank Transfer' => 'Transferencia bancaria',
    'Cash' => 'Efectivo',
    'PayPal' => 'PayPal',
    'Stripe' => 'Stripe',
    'WooCommerce' => 'WooCommerce',
    'Deposit' => 'Depósito',
    'Balance' => 'Saldo',
    'Due' => 'Vencido',
    'Overdue' => 'Atrasado',
    'Free' => 'Gratis',
    
    // ===== NAVIGATION =====
    'Dashboard' => 'Panel de control',
    'Home' => 'Inicio',
    'Menu' => 'Menú',
    'Overview' => 'Resumen',
    'Reports' => 'Informes',
    'Analytics' => 'Analíticas',
    'Statistics' => 'Estadísticas',
    'Notifications' => 'Notificaciones',
    'Messages' => 'Mensajes',
    'Inbox' => 'Bandeja de entrada',
    'Outbox' => 'Bandeja de salida',
    'Sent' => 'Enviado',
    'Drafts' => 'Borradores',
    'Trash' => 'Papelera',
    'Archive' => 'Archivo',
    'History' => 'Historial',
    'Log' => 'Registro',
    'Logs' => 'Registros',
    
    // ===== FORMS =====
    'Form' => 'Formulario',
    'Field' => 'Campo',
    'Fields' => 'Campos',
    'Label' => 'Etiqueta',
    'Placeholder' => 'Marcador de posición',
    'Value' => 'Valor',
    'Text' => 'Texto',
    'Number' => 'Número',
    'Email Address' => 'Dirección de correo electrónico',
    'Phone Number' => 'Número de teléfono',
    'First Name' => 'Nombre',
    'Last Name' => 'Apellido',
    'Full Name' => 'Nombre completo',
    'Company' => 'Empresa',
    'Website' => 'Sitio web',
    'Message' => 'Mensaje',
    'Comment' => 'Comentario',
    'Comments' => 'Comentarios',
    'Review' => 'Reseña',
    'Reviews' => 'Reseñas',
    'Rating' => 'Calificación',
    'Feedback' => 'Comentarios',
    
    // ===== MESSAGES =====
    'Saved successfully.' => 'Guardado correctamente.',
    'Deleted successfully.' => 'Eliminado correctamente.',
    'Updated successfully.' => 'Actualizado correctamente.',
    'Created successfully.' => 'Creado correctamente.',
    'Changes saved.' => 'Cambios guardados.',
    'No changes made.' => 'Sin cambios.',
    'Are you sure?' => '¿Está seguro?',
    'Are you sure you want to delete this?' => '¿Está seguro de que desea eliminar esto?',
    'This action cannot be undone.' => 'Esta acción no se puede deshacer.',
    'Something went wrong.' => 'Algo salió mal.',
    'Please try again.' => 'Por favor, inténtelo de nuevo.',
    'An error occurred.' => 'Se produjo un error.',
    'Invalid input.' => 'Entrada no válida.',
    'Required field.' => 'Campo requerido.',
    'Invalid email address.' => 'Dirección de correo electrónico no válida.',
    'Invalid phone number.' => 'Número de teléfono no válido.',
    'No results found.' => 'No se encontraron resultados.',
    'No items found.' => 'No se encontraron elementos.',
    'No data available.' => 'No hay datos disponibles.',
    
    // ===== PLUGIN-SPECIFIC =====
    'LazyBookings' => 'LazyBookings',
    'Add New Appointment' => 'Añadir nueva cita',
    'Edit Appointment' => 'Editar cita',
    'Delete Appointment' => 'Eliminar cita',
    'View Appointment' => 'Ver cita',
    'Appointment Details' => 'Detalles de la cita',
    'Appointment Status' => 'Estado de la cita',
    'Appointment created.' => 'Cita creada.',
    'Appointment updated.' => 'Cita actualizada.',
    'Appointment deleted.' => 'Cita eliminada.',
    'Appointment confirmed.' => 'Cita confirmada.',
    'Appointment cancelled.' => 'Cita cancelada.',
    'Add New Booking' => 'Añadir nueva reserva',
    'Edit Booking' => 'Editar reserva',
    'Delete Booking' => 'Eliminar reserva',
    'View Booking' => 'Ver reserva',
    'Booking Details' => 'Detalles de la reserva',
    'Booking Status' => 'Estado de la reserva',
    'Booking created.' => 'Reserva creada.',
    'Booking updated.' => 'Reserva actualizada.',
    'Booking deleted.' => 'Reserva eliminada.',
    'Booking confirmed.' => 'Reserva confirmada.',
    'Booking cancelled.' => 'Reserva cancelada.',
    'Add New Customer' => 'Añadir nuevo cliente',
    'Edit Customer' => 'Editar cliente',
    'Delete Customer' => 'Eliminar cliente',
    'View Customer' => 'Ver cliente',
    'Customer Details' => 'Detalles del cliente',
    'Customer saved.' => 'Cliente guardado.',
    'Add New Service' => 'Añadir nuevo servicio',
    'Edit Service' => 'Editar servicio',
    'Delete Service' => 'Eliminar servicio',
    'View Service' => 'Ver servicio',
    'Service Details' => 'Detalles del servicio',
    'Service saved.' => 'Servicio guardado.',
    'Add New Staff' => 'Añadir nuevo personal',
    'Edit Staff' => 'Editar personal',
    'Delete Staff' => 'Eliminar personal',
    'Add New Resource' => 'Añadir nuevo recurso',
    'Edit Resource' => 'Editar recurso',
    'Delete Resource' => 'Eliminar recurso',
    'Add New Room' => 'Añadir nueva habitación',
    'Edit Room' => 'Editar habitación',
    'Delete Room' => 'Eliminar habitación',
    'Room Type' => 'Tipo de habitación',
    'Room Types' => 'Tipos de habitación',
    'Room Number' => 'Número de habitación',
    'Room Name' => 'Nombre de la habitación',
    'Room Status' => 'Estado de la habitación',
    'Bed Type' => 'Tipo de cama',
    'Number of Beds' => 'Número de camas',
    'Max Guests' => 'Máximo de huéspedes',
    'Max Capacity' => 'Capacidad máxima',
    'Price per Night' => 'Precio por noche',
    'Per Night' => 'Por noche',
    'Per Person' => 'Por persona',
    'Working Hours' => 'Horario laboral',
    'Business Hours' => 'Horario comercial',
    'Opening Hours' => 'Horario de apertura',
    'Start Date' => 'Fecha de inicio',
    'End Date' => 'Fecha de fin',
    'Start Time' => 'Hora de inicio',
    'End Time' => 'Hora de fin',
    'Date Range' => 'Rango de fechas',
    'Time Range' => 'Rango horario',
    'Select Date' => 'Seleccionar fecha',
    'Select Time' => 'Seleccionar hora',
    'Select Service' => 'Seleccionar servicio',
    'Select Staff' => 'Seleccionar personal',
    'Select Customer' => 'Seleccionar cliente',
    'Select Room' => 'Seleccionar habitación',
    'Select Status' => 'Seleccionar estado',
    'All Appointments' => 'Todas las citas',
    'All Bookings' => 'Todas las reservas',
    'All Customers' => 'Todos los clientes',
    'All Services' => 'Todos los servicios',
    'All Staff' => 'Todo el personal',
    'All Rooms' => 'Todas las habitaciones',
    'No Appointments' => 'Sin citas',
    'No Bookings' => 'Sin reservas',
    'No Customers' => 'Sin clientes',
    'No Services' => 'Sin servicios',
    'Total Bookings' => 'Total de reservas',
    'Total Revenue' => 'Ingresos totales',
    'Total Customers' => 'Total de clientes',
    'Book Now' => 'Reservar ahora',
    'Book' => 'Reservar',
    'Reserve' => 'Reservar',
    'Check Availability' => 'Comprobar disponibilidad',
    'View Calendar' => 'Ver calendario',
    'Calendar View' => 'Vista de calendario',
    'List View' => 'Vista de lista',
    'Day View' => 'Vista de día',
    'Week View' => 'Vista de semana',
    'Month View' => 'Vista de mes',
    'Diagnostics' => 'Diagnósticos',
    'Documentation' => 'Documentación',
    'Support' => 'Soporte',
    'Branding' => 'Marca',
    'Design' => 'Diseño',
    'Appearance' => 'Apariencia',
    'Colors' => 'Colores',
    'Primary Color' => 'Color primario',
    'Secondary Color' => 'Color secundario',
    'Accent Color' => 'Color de acento',
    'Background Color' => 'Color de fondo',
    'Text Color' => 'Color del texto',
    'Border Color' => 'Color del borde',
    'Error Color' => 'Color de error',
    'Success Color' => 'Color de éxito',
    'Warning Color' => 'Color de advertencia',
    'Font Family' => 'Familia de fuentes',
    'Font Size' => 'Tamaño de fuente',
    'Border Radius' => 'Radio del borde',
    'Border Width' => 'Ancho del borde',
    'Custom CSS' => 'CSS personalizado',
    'Automation' => 'Automatización',
    'Automations' => 'Automatizaciones',
    'Rule' => 'Regla',
    'Rules' => 'Reglas',
    'Trigger' => 'Disparador',
    'Triggers' => 'Disparadores',
    'Action' => 'Acción',
    'Condition' => 'Condición',
    'Conditions' => 'Condiciones',
    'Add Rule' => 'Añadir regla',
    'Edit Rule' => 'Editar regla',
    'Delete Rule' => 'Eliminar regla',
    'Rule saved.' => 'Regla guardada.',
    'Rule deleted.' => 'Regla eliminada.',
    'Template' => 'Plantilla',
    'Templates' => 'Plantillas',
    'Email Template' => 'Plantilla de correo',
    'Add Template' => 'Añadir plantilla',
    'Edit Template' => 'Editar plantilla',
    'Subject' => 'Asunto',
    'Body' => 'Cuerpo',
    'Send Email' => 'Enviar correo',
    'Send Notification' => 'Enviar notificación',
    'Send Reminder' => 'Enviar recordatorio',
    'Reminder' => 'Recordatorio',
    'Reminders' => 'Recordatorios',
    'Notification' => 'Notificación',
    'Email Notifications' => 'Notificaciones por correo',
    'SMS Notifications' => 'Notificaciones por SMS',
    'Push Notifications' => 'Notificaciones push',
    'AI' => 'IA',
    'AI Settings' => 'Configuración de IA',
    'AI Provider' => 'Proveedor de IA',
    'AI Enabled' => 'IA habilitada',
    'AI Settings saved.' => 'Configuración de IA guardada.',
    'Coupon' => 'Cupón',
    'Coupons' => 'Cupones',
    'Coupon Code' => 'Código de cupón',
    'Discount Code' => 'Código de descuento',
    'Apply Coupon' => 'Aplicar cupón',
    'Remove Coupon' => 'Eliminar cupón',
    'WooCommerce Integration' => 'Integración con WooCommerce',
    'Google Calendar' => 'Google Calendar',
    'Stripe Integration' => 'Integración con Stripe',
    'PayPal Integration' => 'Integración con PayPal',
    'API Key' => 'Clave API',
    'Secret Key' => 'Clave secreta',
    'Webhook' => 'Webhook',
    'Webhooks' => 'Webhooks',
    'Webhook URL' => 'URL del webhook',
    'Privacy' => 'Privacidad',
    'Privacy Policy' => 'Política de privacidad',
    'Terms' => 'Términos',
    'Terms of Service' => 'Términos de servicio',
    'GDPR' => 'RGPD',
    'Data Retention' => 'Retención de datos',
    'Export Data' => 'Exportar datos',
    'Delete Data' => 'Eliminar datos',
    'Anonymize' => 'Anonimizar',
    'Setup Wizard' => 'Asistente de configuración',
    'Getting Started' => 'Comenzar',
    'Quick Start' => 'Inicio rápido',
    'Skip' => 'Omitir',
    'Finish' => 'Finalizar',
    'Complete Setup' => 'Completar configuración',
    
    // ===== VALIDATION & ERRORS =====
    'An unexpected error occurred. Please try again or contact support.' => 'Se produjo un error inesperado. Por favor, inténtelo de nuevo o contacte con soporte.',
    'Could not save customer. Please try again.' => 'No se pudo guardar el cliente. Por favor, inténtelo de nuevo.',
    'Could not save service. Please try again.' => 'No se pudo guardar el servicio. Por favor, inténtelo de nuevo.',
    'Could not delete appointment.' => 'No se pudo eliminar la cita.',
    'Could not update appointment.' => 'No se pudo actualizar la cita.',
    'Could not save the appointment to the database.' => 'No se pudo guardar la cita en la base de datos.',
    'Invalid request. Please check your input and try again.' => 'Solicitud no válida. Por favor, revise su entrada e inténtelo de nuevo.',
    'Please enter a valid customer email.' => 'Por favor, introduzca un correo electrónico de cliente válido.',
    'Please enter valid start and end dates.' => 'Por favor, introduzca fechas de inicio y fin válidas.',
    'Payment failed. Please try again.' => 'El pago falló. Por favor, inténtelo de nuevo.',
    'Authentication required. Please log in.' => 'Se requiere autenticación. Por favor, inicie sesión.',
    'Settings saved.' => 'Configuración guardada.',
    'Design saved.' => 'Diseño guardado.',
    'Color saved.' => 'Color guardado.',
    'Working hours saved.' => 'Horario laboral guardado.',
    'Exception created.' => 'Excepción creada.',
    'Exception deleted.' => 'Excepción eliminada.',
    'Guest saved.' => 'Huésped guardado.',
    'Branding settings saved successfully.' => 'Configuración de marca guardada correctamente.',
    'Could not change language. Please try again.' => 'No se pudo cambiar el idioma. Por favor, inténtelo de nuevo.',
    'Network error. Please try again.' => 'Error de red. Por favor, inténtelo de nuevo.',
    
    // ===== MISC =====
    'Language' => 'Idioma',
    'Select Language' => 'Seleccionar idioma',
    'English' => 'Inglés',
    'German' => 'Alemán',
    'Spanish' => 'Español',
    'French' => 'Francés',
    'Italian' => 'Italiano',
    'Portuguese' => 'Portugués',
    'Currency' => 'Moneda',
    'Timezone' => 'Zona horaria',
    'Time Zone' => 'Zona horaria',
    'Date Format' => 'Formato de fecha',
    'Time Format' => 'Formato de hora',
    '24-hour' => '24 horas',
    '12-hour' => '12 horas',
    'per night' => 'por noche',
    'per person' => 'por persona',
    'per hour' => 'por hora',
    'per day' => 'por día',
    'per week' => 'por semana',
    'per month' => 'por mes',
    'Daily' => 'Diario',
    'Weekly' => 'Semanal',
    'Monthly' => 'Mensual',
    'Yearly' => 'Anual',
    'Credits' => 'Créditos',
    'Package' => 'Paquete',
    'Packages' => 'Paquetes',
    'Waitlist' => 'Lista de espera',
    'Queue' => 'Cola',
    '30 Days' => '30 días',
    '60 Days' => '60 días',
    '90 Days' => '90 días',
    '1 Year' => '1 año',
    
    // ===== PLACEHOLDERS WITH %s/%d =====
    '%s is required' => '%s es requerido',
    '%s must be a number' => '%s debe ser un número',
    '%s must be a valid email' => '%s debe ser un correo electrónico válido',
    '%s must be a valid URL' => '%s debe ser una URL válida',
    '%s must be at least %d characters' => '%s debe tener al menos %d caracteres',
    '%s must be no more than %d characters' => '%s no debe tener más de %d caracteres',
    '%s format is invalid' => 'El formato de %s no es válido',
    '%s saved successfully.' => '%s guardado correctamente.',
    '%d services deleted successfully.' => '%d servicios eliminados correctamente.',
    '%d appointments found.' => '%d citas encontradas.',
    '%d bookings found.' => '%d reservas encontradas.',
    '%d customers found.' => '%d clientes encontrados.',
];

echo "📂 Loading PO file...\n";

$content = file_get_contents($po_file);

// Update header for Spanish
$content = preg_replace(
    '/^"Language: .*?"$/m',
    '"Language: es_ES\n"',
    $content
);

// Parse and translate
$lines = explode("\n", $content);
$result = [];
$current_msgid = '';
$in_msgid = false;
$in_msgstr = false;
$msgstr_empty = false;
$translated_count = 0;
$total_empty = 0;

for ($i = 0; $i < count($lines); $i++) {
    $line = $lines[$i];
    
    // Track msgid
    if (preg_match('/^msgid "(.*)"$/', $line, $m)) {
        $current_msgid = $m[1];
        $in_msgid = true;
        $in_msgstr = false;
        $result[] = $line;
        continue;
    }
    
    // Multi-line msgid continuation
    if ($in_msgid && preg_match('/^"(.*)"$/', $line, $m)) {
        $current_msgid .= $m[1];
        $result[] = $line;
        continue;
    }
    
    // Track msgstr
    if (preg_match('/^msgstr "(.*)"$/', $line, $m)) {
        $in_msgid = false;
        $in_msgstr = true;
        $msgstr_value = $m[1];
        
        // Check if empty and we have translation
        if ($msgstr_value === '' && $current_msgid !== '' && isset($dictionary[$current_msgid])) {
            $total_empty++;
            $translation = $dictionary[$current_msgid];
            $result[] = 'msgstr "' . addcslashes($translation, '"\\') . '"';
            $translated_count++;
        } else {
            if ($msgstr_value === '' && $current_msgid !== '') {
                $total_empty++;
            }
            $result[] = $line;
        }
        continue;
    }
    
    // Multi-line msgstr (skip if we just translated)
    if ($in_msgstr && preg_match('/^"(.*)"$/', $line, $m)) {
        $result[] = $line;
        continue;
    }
    
    // Reset state on empty line
    if (trim($line) === '') {
        $in_msgid = false;
        $in_msgstr = false;
        $current_msgid = '';
    }
    
    $result[] = $line;
}

// Save
file_put_contents($po_file, implode("\n", $result));

$remaining = $total_empty - $translated_count;
echo "✅ Translated $translated_count of $total_empty empty strings\n";
echo "📝 Remaining empty: $remaining\n";
